package org.example;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class KnapsackGUI {
    private JTextField number_field;
    private JTextField seed_field;
    private JTextField capacity_field;
    private JButton button1;
    private JTextArea Problem_text;
    private JTextArea Result_text;
    private JPanel panel1;

    KnapsackGUI() {
        button1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    int number = Integer.parseInt(number_field.getText());
                    int seed = Integer.parseInt(seed_field.getText());
                    int capacity = Integer.parseInt(capacity_field.getText());
                    Problem problem = new Problem(number, seed, 1, 10);
                    Problem_text.setText(problem.toString());
                    Result result = problem.Solve(capacity);
                    Result_text.setText(result.toString());
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(panel1, "Please enter valid numbers.");
                }
            }
        });
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setEnabled(false);
        panel1.setForeground(new Color(-1755635));
        final JLabel label1 = new JLabel();
        label1.setBackground(new Color(-1755635));
        label1.setText("Insert number:       ");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weighty = 0.1;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label1, gbc);
        number_field = new JTextField();
        number_field.setHorizontalAlignment(0);
        number_field.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(number_field, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Insert seed:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weighty = 0.1;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label2, gbc);
        seed_field = new JTextField();
        seed_field.setHorizontalAlignment(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(seed_field, gbc);
        capacity_field = new JTextField();
        capacity_field.setHorizontalAlignment(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(capacity_field, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Insert capacity:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weighty = 0.1;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label3, gbc);
        button1 = new JButton();
        button1.setText("Calculate");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(button1, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Problem instance:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 12.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 10;
        panel1.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Result:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.weightx = 1.5;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label5, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridheight = 3;
        gbc.weightx = 0.7;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(scrollPane1, gbc);
        Problem_text = new JTextArea();
        Problem_text.setText("");
        scrollPane1.setViewportView(Problem_text);
        final JScrollPane scrollPane2 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.gridheight = 2;
        gbc.weightx = 0.7;
        gbc.weighty = 0.3;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(scrollPane2, gbc);
        Result_text = new JTextArea();
        scrollPane2.setViewportView(Result_text);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("KnapsackGUI");
        frame.setContentPane(new KnapsackGUI().panel1);
        frame.setPreferredSize(new Dimension(400, 300));
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);

    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}

