// <auto-generated />
using System;
using LAB2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LAB2.Migrations
{
    [DbContext(typeof(History))]
    partial class HistoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("LAB2.Data", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("mainId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("mainId");

                    b.ToTable("Data_history");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            name = "Wrocław"
                        },
                        new
                        {
                            Id = 2,
                            name = "Wrocław"
                        },
                        new
                        {
                            Id = 3,
                            name = "Wrocław"
                        });
                });

            modelBuilder.Entity("LAB2.Main", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("feels_like")
                        .HasColumnType("REAL");

                    b.Property<int>("humidity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("pressure")
                        .HasColumnType("INTEGER");

                    b.Property<float>("temp")
                        .HasColumnType("REAL");

                    b.Property<float>("temp_max")
                        .HasColumnType("REAL");

                    b.Property<float>("temp_min")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Main");
                });

            modelBuilder.Entity("LAB2.Weather", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("DataId");

                    b.ToTable("Weather");
                });

            modelBuilder.Entity("LAB2.Data", b =>
                {
                    b.HasOne("LAB2.Main", "main")
                        .WithMany()
                        .HasForeignKey("mainId");

                    b.Navigation("main");
                });

            modelBuilder.Entity("LAB2.Weather", b =>
                {
                    b.HasOne("LAB2.Data", null)
                        .WithMany("weather")
                        .HasForeignKey("DataId");
                });

            modelBuilder.Entity("LAB2.Data", b =>
                {
                    b.Navigation("weather");
                });
#pragma warning restore 612, 618
        }
    }
}
